apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-nginx
  name: flask-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: flask-app
        image: 540546280025.dkr.ecr.eu-central-1.amazonaws.com/flask-app:latest
        envFrom:
          - configMapRef:
             name: mysql-configmap
               #- secretRef:
            #name: mysql-secret
        ports:
        - containerPort: 5002
