apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: ingress-nginx
spec:
  volumeName: app-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
